config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get '/login', to: 'sessions#new', as: 'login'
  get '/signup', to: 'users#new', as: 'signup'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: %i[new create destroy]
  resources :password_resets

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string
#  name                   :string
#  password_digest        :string
#  password_reset_token   :string
#  password_reset_sent_at :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_length_of :password, minimum: 8
  has_secure_password

  def send_password_reset
    generate_token(:password_reset_token)
    password_reset_sent_at = Time.zone.now
    save(validate: false)

    UserMailer.forgot_password(self).deliver_now
  end

  private

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  private

  def authenticate_user!
    redirect_to root_path, alert: 'Please login first!' unless current_user
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])

    user&.send_password_reset
    flash[:notice] = 'E-mail sent with password reset instructions.'
    redirect_to new_session_path
  end

  def edit
    @user = User.find_by_password_reset_token(params[:id])

    redirect_to new_session_path unless @user
  end

  def update
    @user = User.find_by_password_reset_token(params[:id])
    return redirect_to new_session_path unless @user

    if @user.password_reset_sent_at < 6.hour.ago
      flash[:notice] = 'Password reset has expired'
      redirect_to new_password_reset_path
    elsif @user.update(user_params)
      flash[:notice] = 'Password has been reset!'
      redirect_to new_session_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %w[show edit update destroy]
  before_action :authenticate_user!, only: %w[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome(@user).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title
      | IncubitDemo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #container
      #user_header
        - if current_user
          |  Logged in as&nbsp;
          = current_user.email
          | &nbsp;
          = link_to "Log Out", logout_path
        - else
          = link_to "Sign Up", signup_path
          |&nbsp;or&nbsp;
          = link_to "Log In", login_path
          |&nbsp;or&nbsp;
          = link_to "Forgot password?", new_password_reset_path
      - flash.each do |name, msg|
        = content_tag :div, msg, id: "flash_#{name}"
      = yield

app/views/password_resets/edit.html.slim
h1
  | Reset Password
= form_for @user, url: password_reset_path(params[:id]) do |f|
  - if @user.errors.any?
    .error_messages
      h2
        | Form is invalid
      ul
        - for message in @user.errors.full_messages
          li
            = message
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Update password'

app/views/password_resets/new.html.slim
h1
  | Reset Password

= form_tag password_resets_path, method: :post do
  .field
    = label_tag :email
    = email_field_tag :email, params[:email]
  .actions
    = submit_tag "Reset Password"

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password

  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
br
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Incubit Demo

= link_to 'Edit', edit_user_path(current_user) if current_user

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
h1 Profile page

p#notice = notice
p
  strong Email:
  = @user.email
p
  strong Password:
  = @user.password

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path